### ISSUE TITLE
Aruba Performance Dischi Private Cloud 2

### ISSUE THREAD

**Issue by adminstudioeco** [adminstudioeco/public#1]
# Test comando MySQL
Esecuzione del comando singolo MySQL dalla stessa macchina dove risiede il DB: ```date; sudo mysql formalms_mps_prod  -e "optimize table mpsst_raw_in_assenze;" ; date```

## MPS-UAT (sede):
Tempo di esecuzione: 2s
![image](https://user-images.githubusercontent.com/53079450/114507872-05888e80-9c34-11eb-8081-750a188e097b.png)
## MPS-PROD-DB (aruba pc2):
Tempo di esecuzione: 15s
![image](https://user-images.githubusercontent.com/53079450/114507945-1e913f80-9c34-11eb-8875-ee5c3e6ff256.png)

# Test Importazione CROND
## MPS-UAT (sede):
Tempo di esecuzione: 26s + 2s
![image](https://user-images.githubusercontent.com/53079450/114429586-d2a3b380-9bbd-11eb-8dd3-e069640278dd.png)
## MPS-PROD-WEB (aruba pc2):
Tempo di esecuzione: 2m + 23s
![image](https://user-images.githubusercontent.com/53079450/114430125-66757f80-9bbe-11eb-941f-923b0d3d7490.png)

# Test disco DD 
Scrittura di 1Mega x 1000 volte.
```dd if=/dev/zero of=test1.img bs=1M count=1000 oflag=dsync```
## MPS-UAT (sede):
Scrittura su disco:  429 MB/s
![image](https://user-images.githubusercontent.com/53079450/114439815-b3ab1e80-9bc9-11eb-9dc4-853e481d8467.png)
## MPS-PROD-DB (aruba pc2):
Scrittura su disco:  138 MB/s
![image](https://user-images.githubusercontent.com/53079450/114439664-86f70700-9bc9-11eb-9dab-4b72dca268a3.png)
## MPS-PROD-WEB (aruba pc2):
Scrittura su disco:  133 MB/s
![image](https://user-images.githubusercontent.com/53079450/114439868-c02f7700-9bc9-11eb-8311-91b46999ab29.png)

**Comment by galvianistudioeco** [comment]
Consci dello stato dei dischi forniti da aruba archivio la iussue. Se si dovessero presenrtare problemi riapriremo la discussione.
